name: VeraCore Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        echo "Installing dependencies from requirements.txt..."
        cat requirements.txt
        pip install -r requirements.txt -v
    
    - name: Create .env file from secrets
      run: |
        echo "USERNAME=${{ secrets.USERNAME }}" > .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        echo "SYSTEM_ID=${{ secrets.SYSTEM_ID }}" >> .env
        echo "W_TOKEN=${{ secrets.W_TOKEN }}" >> .env
        echo "SHAREPOINT_CLIENT_ID=${{ secrets.SHAREPOINT_CLIENT_ID }}" >> .env
        echo "SHAREPOINT_CLIENT_SECRET=${{ secrets.SHAREPOINT_CLIENT_SECRET }}" >> .env
        echo ".env file created successfully"

    - name: Debug Environment Variables
      run: |
        echo "USERNAME is set: $([[ -n "$USERNAME" ]] && echo 'YES' || echo 'NO')"
        echo "PASSWORD is set: $([[ -n "$PASSWORD" ]] && echo 'YES' || echo 'NO')"
        echo "SYSTEM_ID is set: $([[ -n "$SYSTEM_ID" ]] && echo 'YES' || echo 'NO')"
        echo "USERNAME length: ${#USERNAME}"
        echo "SYSTEM_ID value: $SYSTEM_ID"
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SYSTEM_ID: ${{ secrets.SYSTEM_ID }}
        W_TOKEN: ${{ secrets.W_TOKEN }}
        SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
        SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}

    - name: Run VeraCore Pipeline
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SYSTEM_ID: ${{ secrets.SYSTEM_ID }}
        W_TOKEN: ${{ secrets.W_TOKEN }}
        SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
        SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      run: python reports.py
        


